version: "3"

services:
  db-xss:
    image: mysql:8.0.36
    ports:
      - '3310:3306'
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
#      MYSQL_USER: 'root'
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      # MYSQL_HOST: ''
    networks:
      - openlxp
  app:
    container_name: openlxp-xss
    build:
      context: .
    ports:
      - "8010:8020"
    command: >
      sh -c ". /opt/app/start-app.sh"
    environment:
      CORS_ALLOWED_ORIGINS: "${CORS_ALLOWED_ORIGINS}"
      DB_HOST: "${DB_HOST}"
      DB_NAME: "${DB_NAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_USER: "${DB_USER}"
      DJANGO_SUPERUSER_EMAIL: "${DJANGO_SUPERUSER_EMAIL}"
      DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD}"
      DJANGO_SUPERUSER_USERNAME: "${DJANGO_SUPERUSER_USERNAME}"
      ENTITY_ID: "${ENTITY_ID}"
      SECRET_KEY_VAL: "${SECRET_KEY_VAL}"
      SP_PRIVATE_KEY: "${SP_PRIVATE_KEY}"
      SP_PUBLIC_CERT: "${SP_PUBLIC_CERT}"
    volumes:
      - ./app:/opt/app/openlxp-xss
    depends_on:
      - db-xss
    networks:
      - openlxp
volumes:
  data01:
    driver: local
networks:
  openlxp:
    external: true
