# Generated by Django 3.2.25 on 2024-10-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LCVTermDjangoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('term', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'LCV Term',
                'verbose_name_plural': 'LCV Terms',
            },
        ),
        migrations.CreateModel(
            name='ProviderDjangoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
        migrations.CreateModel(
            name='UIDCounterDjangoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'UID Counter',
                'verbose_name_plural': 'UID Counters',
            },
        ),
    ]
