# Generated by Django 3.2.25 on 2024-10-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastGeneratedUID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Last Generated UID',
                'verbose_name_plural': 'Last Generated UIDs',
            },
        ),
    ]
