# Generated by Django 3.2.25 on 2024-10-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uid', '0002_lastgenerateduid'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedUIDLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generator_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Generated UID Log',
                'verbose_name_plural': 'Generated UID Logs',
            },
        ),
    ]
