# Generated by Django 3.2.25 on 2024-10-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uid', '0003_generateduidlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateduidlog',
            name='lcv_terms',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generateduidlog',
            name='provider',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
