# Generated by Django 3.2.25 on 2024-11-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uid', '0005_auto_20241104_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateduidlog',
            name='uid_full',
            field=models.CharField(default='', max_length=255),
        ),
    ]
