# Generated by Django 3.2.25 on 2024-11-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uid', '0006_generateduidlog_uid_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateduidlog',
            name='uid',
            field=models.CharField(default='', max_length=255),
        ),
    ]
