# Generated by Django 3.2.25 on 2024-11-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uid', '0007_alter_generateduidlog_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateduidlog',
            name='uid',
            field=models.CharField(default='UNKNOWN', max_length=255),
        ),
        migrations.AlterField(
            model_name='generateduidlog',
            name='uid_full',
            field=models.CharField(default='UNKNOWN', max_length=255),
        ),
    ]
