# Generated by Django 3.2.25 on 2024-11-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uid', '0008_auto_20241104_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCVTermDjangoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=255)),
                ('term', models.CharField(max_length=255)),
                ('echelon', models.CharField(max_length=255)),
                ('structure', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'LCV Term',
                'verbose_name_plural': 'LCV Terms',
            },
        ),
    ]
