# Generated by Django 4.2.16 on 2024-10-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230901_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='mapping',
            field=models.ManyToManyField(blank=True, to='core.term'),
        ),
    ]
