# Generated by Django 3.2.25 on 2024-12-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230901_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Custom Page',
                'verbose_name_plural': 'Custom Page',
                'managed': False,
            },
        ),
    ]
