# Generated by Django 4.2.23 on 2025-07-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_term_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='multiple_expected',
            field=models.BooleanField(default=False, help_text='Whether multiple values are expected for this Term'),
        ),
        migrations.AddField(
            model_name='term',
            name='type',
            field=models.CharField(choices=[('Learning Resource', 'Learning Resource'), ('Learning Event', 'Learning Event'), ('Both', 'Both')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
