# Generated by Django 3.2.25 on 2024-12-23 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dummymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyModel',
        ),
    ]
