# Generated by Django 4.2.23 on 2025-07-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_term_multiple_expected_term_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='type',
        ),
        migrations.AddField(
            model_name='term',
            name='learning_type',
            field=models.CharField(blank=True, choices=[('Learning Resource', 'Learning Resource'), ('Learning Event', 'Learning Event'), ('Both', 'Both')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='multiple_expected',
            field=models.BooleanField(default=True, help_text='Whether multiple values are expected for this Term'),
        ),
    ]
