# Generated by Django 4.2.23 on 2025-08-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_term_type_term_learning_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='learning_type',
        ),
    ]
